### ISSUE TITLE
cannot use mp3 as sound element

### ISSUE THREAD

**Issue by fabton1963** [fkS124/Pygame-Engine#1]
If I try to run test-example.py I get the following error
  File "c:\sviluppo\python\gitprojects\Pygame-Engine\pygame_engine\__init__.py", line 97, in load_sound
    engine.sound_manager.sounds[key] = pg.mixer.Sound(path)
pygame.error: Unable to open file './outputs/jump sound2.mp3'

in pygame documentation I see that it cannot handle mp3 files as sound just as music

if I remove the statement in line 148 and in line 71 the demo works.

**Comment by fkS124** [comment]
What operating system and pygame version are you using ?

Because it runs fine on Windows, pygame2.1.3.dev4
 
I'll look into it later today!

**Comment by fkS124** [comment]
Okay, from my tests, this error is due to your version of pygame.

I can reproduce your error with `pygame2.0.0`, but after `pygame2.1.0` this error is fixed.

**Comment by fabton1963** [comment]
ok ,I'm using 2.1.2 stable.
